spring:
  profiles:
    active: dev
  jackson:
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      ORDER_MAP_ENTRIES_BY_KEYS: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: shu.xai.dataAnalysis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl